name: Publish to PyPI

on:
  push:
    branches:
      - "main"
    paths:
      - "cdxsummary/__init__.py"
  workflow_dispatch:

jobs:
  build-n-publish:
    name: Build and Publish Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Upgrade setuptools and wheel
        run: python -m pip install --user --upgrade setuptools wheel
      - name: Build a binary wheel and a source tarball
        run: python setup.py sdist bdist_wheel
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_PASSWORD }}
